---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[ubuntu]
  - name: centos-6.4
    run_list:
      - recipe[yum]
      - recipe[yum-epel]

suites:
  - name: default
    run_list:
      - recipe[flapjack]
    attributes:
      ruby_installer:
        method: source
        source_version: 2.0.0-p451
