---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[flapjack_test]
      - recipe[flapjack]
    attributes:
      ruby_installer:
        method: source
        source_version: 2.0.0-p451
      flapjack:
        ruby_bin_dir: /usr/local/bin
        contacts:
          manage_all_entity: true
  - name: package
    run_list:
      - recipe[flapjack_test]
      - recipe[flapjack]
    attributes:
      flapjack:
        install_method: package
        version: 0.8.8+20140320045121-1.ubuntu.12.04
